# Generated by Django 3.2.12 on 2023-11-15 02:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('globe2', '0002_city_country_state'),
    ]

    operations = [
        migrations.AlterField(
            model_name='city',
            name='cityCode',
            field=models.CharField(max_length=50, unique=True),
        ),
        migrations.AlterField(
            model_name='city',
            name='cityName',
            field=models.CharField(max_length=50, unique=True),
        ),
        migrations.AlterField(
            model_name='country',
            name='countryCode',
            field=models.CharField(max_length=50, unique=True),
        ),
        migrations.AlterField(
            model_name='country',
            name='phoneCode',
            field=models.IntegerField(max_length=10, unique=True),
        ),
        migrations.AlterField(
            model_name='state',
            name='GST_code',
            field=models.CharField(max_length=50, unique=True),
        ),
        migrations.AlterField(
            model_name='state',
            name='stateName',
            field=models.CharField(max_length=50, unique=True),
        ),
    ]
