# Generated by Django 3.2.12 on 2023-11-15 02:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('globe2', '0003_auto_20231115_0249'),
    ]

    operations = [
        migrations.AlterField(
            model_name='country',
            name='phoneCode',
            field=models.IntegerField(unique=True),
        ),
    ]
