# Generated by Django 3.2.12 on 2023-11-15 04:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('globe2', '0010_country_my_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='country',
            name='my_user',
        ),
    ]
