# Generated by Django 3.2.12 on 2023-11-15 04:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('globe2', '0011_remove_country_my_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='country',
            name='countryCode',
            field=models.CharField(max_length=10, unique=True),
        ),
    ]
