# Generated by Django 3.2.12 on 2023-11-15 04:16

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('globe2', '0012_alter_country_countrycode'),
    ]

    operations = [
        migrations.AddField(
            model_name='country',
            name='my_user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
