# Generated by Django 3.2.12 on 2023-11-15 05:21

from django.db import migrations
from django.apps import apps

#logic to assign random user to countries
def update_null_country(globe2,schema_editor):
    print("i am updating user in country")
    Country =  apps.get_model('globe2','Country')
    user = apps.get_model('globe2','CustomUser')

    country_without_user = Country.objects.filter(my_user__isnull=True)
    batch_size=4
    for i in range(0,len(country_without_user),batch_size):
        record_batch = country_without_user[i:i+batch_size]
        random_user = user.objects.order_by('?').first()

        for country in record_batch:
            country.my_user = random_user
            country.save()

#reverse migration function
def reverse_migration(globe2,schema_editor):
    Country =  apps.get_model('globe2','Country')
    Country.objects.update(my_user=None)

print(" updating done")
class Migration(migrations.Migration):

    dependencies = [
        ('globe2', '0013_country_my_user'),
    ]

    operations = [
    migrations.RunPython(update_null_country, reverse_migration),

    ]
