# Generated by Django 3.2.12 on 2023-11-17 03:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('globe2', '0016_auto_20231116_1236'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='access_token',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='customuser',
            name='refresh_token',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
